name: deepl
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - cython=0.29.32
  - ffmpeg=4.3
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openh264=2.1.1
  - openssl=1.1.1s
  - pillow=9.3.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - pytorch=1.13.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - scipy=1.9.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - torchvision=0.14.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - backcall==0.2.0
      - blessed==1.19.1
      - bresenham==0.2.1
      - build==0.9.0
      - click==8.1.3
      - comm==0.1.2
      - commonmark==0.9.1
      - contourpy==1.0.6
      - croniter==1.3.8
      - cycler==0.11.0
      - debugpy==1.6.5
      - decorator==5.1.1
      - deepdiff==6.2.3
      - distro==1.8.0
      - dnspython==2.2.1
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - efficientnet-pytorch==0.7.1
      - email-validator==1.3.0
      - entrypoints==0.4
      - executing==1.2.0
      - fastapi==0.89.1
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.30
      - httpcore==0.16.3
      - httptools==0.5.0
      - httpx==0.23.3
      - imageio==2.23.0
      - inquirer==3.1.2
      - ipykernel==6.19.4
      - ipython==8.8.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jupyter-client==7.4.8
      - jupyter-core==5.1.2
      - kiwisolver==1.4.4
      - lightning==1.8.6
      - lightning-cloud==0.5.16
      - lightning-utilities==0.5.0
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - multidict==6.0.4
      - munch==2.5.0
      - nest-asyncio==1.5.6
      - networkx==2.8.8
      - opencv-python==4.6.0.66
      - ordered-set==4.1.0
      - orjson==3.8.5
      - parso==0.8.3
      - pathtools==0.1.2
      - pep517==0.13.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==2.6.2
      - pretrainedmodels==0.7.4
      - promise==2.3
      - prompt-toolkit==3.0.36
      - protobuf==3.20.1
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycocotools==2.0
      - pydantic==1.10.4
      - pygments==2.14.0
      - pyjwt==2.6.0
      - pylsd-nova==1.2.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-multipart==0.0.5
      - pytlsd==0.0.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==24.0.1
      - readchar==4.0.3
      - rfc3986==1.5.0
      - rich==13.1.0
      - scikit-build==0.16.4
      - scikit-image==0.19.3
      - segmentation-models-pytorch==0.3.2
      - sentry-sdk==1.12.1
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - smmap==5.0.0
      - stack-data==0.6.2
      - starlette==0.22.0
      - starsessions==1.3.0
      - tensorboardx==2.5.1
      - tifffile==2022.10.10
      - timm==0.6.12
      - torchmetrics==0.11.0
      - tornado==6.2
      - traitlets==5.8.0
      - ujson==5.7.0
      - uvicorn==0.20.0
      - uvloop==0.17.0
      - wandb==0.13.7
      - watchfiles==0.18.1
      - wcwidth==0.2.5
      - websockets==10.4
      - yacs==0.1.8
      - yarl==1.8.2
